### PR TITLE
Optimised sendIntent

### PR DESCRIPTION
**Pull request by abhisheksingh-jsdev**
SendIntent function is optimised. Created a new function encryptMessages in the Chatbox.tsx to encrypt the Messages in the sendIntent by checking the user.

### CODE REVIEW

**Review by corlard3y — CHANGES_REQUESTED** [review]
When i send intents, the chat sidebar section keeps loading and there is this error in the console, you will want to check that break in functionality @abhisheksingh-jsdev 
Screenshot 2022-10-20 at 11 27 12

**Review by mishramonalisha76 — APPROVED** [review]

**Review by mishramonalisha76 — CHANGES_REQUESTED** [review]
Fix Merge conflicts. Rest looks good

**Review by mishramonalisha76 — DISMISSED** [review]
LGTM

**Review by 0xNilesh — DISMISSED** [review]

**Review by mishramonalisha76 — CHANGES_REQUESTED** [review]

**Review by corlard3y — APPROVED** [review]

**Review by mishramonalisha76 — APPROVED** [review]
LGTM

**Pull request merged**
