### PR TITLE
Fix vertical scroll on inbox and spam page

### PR DESCRIPTION
**Pull request by madhurg-epns**

### CODE REVIEW

**Review by corlard3y — APPROVED** [review]

**Comment by zaryab2000** [comment]
If this PR has now been reviewed by both reviewers, @corlard3y and @mishramonalisha76 

Can we close this now?

@madhurg-epns

**Comment by madhurg-epns** [comment]
> If this PR has now been reviewed by both reviewers, @corlard3y and @mishramonalisha76
> 
> Can we close this now?
> 
> @madhurg-epns

@zaryab2000 There seem to be some merge conflicts, I'll resolve those after scrum (currently in backend scrum), and it has been reviewed by both Monalisa and Kolade.

**Comment by zaryab2000** [comment]
Ok - sounds good @madhurg-epns

**Comment by madhurg-epns** [comment]
@zaryab2000 I have fixed the merge conflict.

**Comment by madhurg-epns** [comment]
@0xNilesh This PR has been reviewed by Monalisa and Kolade, later I had to make small change to fix merge conflicts.

**Pull request merged**
