### PR TITLE
Text fixed during intent

### PR DESCRIPTION
**Pull request by abhishek-01k**
If the receiver has PGP keys then then text will be : "Messages are encrypted"
and if the receiver has no PGP keys then the text will be : "Messages are not encrypted till the user accepts the chat request."

### CODE REVIEW

**Comment by mishramonalisha76** [comment]
Sending intent to a new user or old user both gives messages are encrypted instead of the "Messages are not encrypted till the user accepts the chat request."
image

**Review by mishramonalisha76 — CHANGES_REQUESTED** [review]
Sending intent to a new user or old user both gives messages are encrypted instead of the "Messages are not encrypted till the user accepts the chat request."
image

**Review by mishramonalisha76 — APPROVED** [review]

**Comment by zaryab2000** [comment]
If this seems good now, kindly merge it @mishramonalisha76

**Comment by zaryab2000** [comment]
@abhishek-01k -> Any updates on this PR? is the review still pending? @mishramonalisha76

**Comment by zaryab2000** [comment]
@abhishek-01k lemme know if this can be merged 

Cc: @mishramonalisha76

**Pull request closed without merging**
