### PR TITLE
Fix create channel flow to handle user reject transaction

### PR DESCRIPTION
**Pull request by madhurg-epns**
- Fixes `handleCreateChannel` function in `CreateChannel.js` to take the user back to the screen where they can trigger the transaction (to create a channel) again after rejecting it.

### CODE REVIEW

**Comment by zaryab2000** [comment]
@0xNilesh

**Comment by zaryab2000** [comment]
@madhurg-epns is this issue closed now?

**Comment by zaryab2000** [comment]
@corlard3y need to bump up the priority for this and get this resolved. Kindly check on this once.

**Comment by corlard3y** [comment]
Functionality resolved, PR conflicts to be resolved before approval @madhurg-epns

**Comment by madhurg-epns** [comment]
> Functionality resolved, PR conflicts to be resolved before approval @madhurg-epns

Alright @corlard3y, I'll resolve the conflicts.

**Pull request merged**
